DROP SEQUENCE BD_SEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BD_SEQ NOCACHE;

CREATE TABLE BOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(BD_SEQ.NEXTVAL, '이름', '제목테스트', '글 내용 테스트. 어쩌구 저꺼구. JSP 재미있다.', SYSDATE);

update board (bd_no, bd_name, bd_title, bd_content, bd_date)
values(2,"2번 수정중","2번 수정","수정한당",SYSDATE);